[package]
name = "mira-argparse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
clap.workspace = true
mira-target.workspace = true

[lints]
workspace = true
