[package]
name = "mira-progress-bar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
termsize.workspace = true

[lints]
workspace = true
