[package]
name = "mira-spans"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
parking_lot.workspace = true

[lints]
workspace = true
