[package]
name = "mira-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
crossbeam-channel.workspace = true
parking_lot.workspace = true

[lints]
workspace = true
