[package]
name = "mira-lexer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
mira-spans.workspace = true
mira-errors.workspace = true
mira-context.workspace = true

[lints]
workspace = true
