[package]
name = "mira-errors"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
mira-spans.workspace = true
mira-macros.workspace = true

[lints]
workspace = true
